version: '3.8'

services:
  backend:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - h2_data:/app/data

  frontend:
    build:
      context: ./frontend/my-react-app
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  h2_data: